- name: Set node exporter version
  set_fact:
    node_exporter_version: "v1.7.0"

- name: Ensure node-exporter container is running
  community.docker.docker_container:
    name: node-exporter
    image: prom/node-exporter:{{ node_exporter_version }}
    state: started
    restart_policy: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    network_mode: host
    command: >
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
      --path.rootfs=/rootfs
      --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"
