prometheus_version: "latest"
grafana_version: "latest"
loki_version: "latest"
node_exporter_version: "latest"
promtail_version: "latest"
monitor_host: "54.242.81.86"

# Grafana settings
grafana_admin_user: "admin"
grafana_admin_password: "admin123"  # Change this in production

prometheus_targets:
  - aws-node:9100
  - ibm-node:9100

log_labels:
  job: syslog
  host: "{{ inventory_hostname }}"
