---
- name: Install and Configure CloudWatch Agent
  hosts: all
  become: yes
  vars:
    aws_region: "{{ aws_region | default('us-east-1') }}"
    cloudwatch_config_file: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json"

  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - unzip
          - python3-pip
        state: present
        update_cache: yes

    - name: Install AWS CLI
      pip:
        name: awscli
        state: present

    - name: Download CloudWatch Agent
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb
        mode: '0644'

    - name: Install CloudWatch Agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Create CloudWatch Agent config directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Create Node.js application log directory
      file:
        path: /var/log/node-app
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy CloudWatch Agent configuration
      template:
        src: templates/amazon-cloudwatch-agent.json.j2
        dest: "{{ cloudwatch_config_file }}"
        mode: '0644'
      notify: Restart CloudWatch Agent

    - name: Start CloudWatch Agent
      systemd:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes

  handlers:
    - name: Restart CloudWatch Agent
      systemd:
        name: amazon-cloudwatch-agent
        state: restarted 